# Site wide configuration

title:            BENNETTSCASH
locale:           en_AU
url:              


# Jekyll configuration

theme: minimal-mistakes-jekyll
permalink:   /:categories/:title/
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Chris Bennetts-Cash
  avatar: bio-photo.jpg
  bio: "Climber. Software engineer. Audio geek."
  email: chris@bennettscash.id.au
  disqus-shortname: #something
  twitter: chris_bc
  facebook: bennettscash
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: chris-bc
  stackoverflow: 1517/chris-b-c
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess", "gallery"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
